If:                               # for C
  PathMatch: [.*\.h, .*\.c]
CompileFlags:
<<<<<<< HEAD
  Add: [-Wall, -Wextra, -std=c2x]
=======
  Add: [-Wall, -Wextra, -std=c2x, -xc]
>>>>>>> 9febced (clangd)
  Compiler: gcc
---
If:                              # for C++
  PathMatch: [.*\.hpp, .*\.cpp]
CompileFlags:
  Add: [-Wall, -Wextra, -std=c++2c, -xc++]
  Compiler: g++
---
# index Standart Lib for Completion
Index:
  StandardLibrary: Yes

# Tips for Modern style
Diagnostics:
  ClangTidy:
    Add: [performance*, modernize*, readability*]
    Remove: [modernize-use-trailing-return-type, readability-braces-around-statements, readability-isolate-declaration, readability-identifier-length]
    CheckOptions:
      readability-identifier-naming.VariableCase: snake_case

AllScopes: Yes

InlayHints:
  BlockEnd: No
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24

Hover:
  ShowAKA: Yes

# Formatting
# BasedOnStyle: LLVM
# IndentWidth: 4
