If:                              # for C++
  PathMatch: [.*\.hpp, .*\.cpp]
CompileFlags:
  Add: [-Wall, -Wextra, -std=c++2b]
  Compiler: g++
---
If:                               # for C
  PathMatch: [.*\.h, .*\.c]
CompileFlags:
  Add: [-Wall, -Wextra, -std=c23]
  Compiler: gcc
---
# index Standart Lib for Completion
Index:
  StandardLibrary: Yes

# Tips for Modern style
Diagnostics:
  ClangTidy:
    Add: modernize*
    Remove: modernize-use-trailing-return-type

AllScopes: Yes

InlayHints:
  BlockEnd: No
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24

Hover:
  ShowAKA: Yes

# Formatting
# BasedOnStyle: LLVM
# IndentWidth: 4
